version: '2'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
      - '5001:5001'
    privileged: true
    volumes:
      - 'jenkins_home2:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  jenkins_home2:
    driver: local
