pipeline{
     environment {
       IMAGE_NAME = "djangoapp"
       IMAGE_TAG = "latest"
     }
    agent none
    stages {
        stage('prepare context') {
            agent any
            steps {
               script {
                 sh '''
                   docker stop $IMAGE_NAME
                   docker rm $IMAGE_NAME
		   docker rmi $IMAGE_NAME
                 '''
                }
            }
        }
        stage("build"){
	    agent any
            steps {
                sh """
                    docker build -t $IMAGE_NAME:$IMAGE_TAG  .
                """
            }
        }
        stage("run"){
	    agent any
            steps{
                sh """
		    docker build -t $IMAGE_NAME:$IMAGE_TAG  .
                    docker-compose up
		    sleep 5
                """
            }
        }
       stage('Test image') {
           agent any
           steps {
              script {
                sh '''
                    curl http://127.0.0.1:8000
                '''
              }
           }
	}
      stage('Clean Container') {
          agent any
          steps {
             script {
               sh '''
                 docker stop $IMAGE_NAME
                 docker rm $IMAGE_NAME
               '''
             }
          }
     }
    }
}
