
pipeline{
     environment {
       IMAGE_NAME = "djangoapp"
       IMAGE_TAG = "latest"
     }
    agent none
    stages {
        stage("build"){
	    agent any
            steps {
                sh """
                    docker build -t $IMAGE_NAME:$IMAGE_TAG  .
                """
            }
        }
        stage("run"){
	    agent any
            steps{
                sh """
		    docker build -t $IMAGE_NAME:$IMAGE_TAG  .
                    docker-compose up -d
		    sleep 5
                """
            }
        }
       stage('Test image') {
           agent any
           steps {
              script {
                sh '''
                    curl -L "http://192.168.99.10:8000"
                '''
              }
           }
	}
      stage('Clean Container') {
          agent any
          steps {
             script {
               sh '''
                 docker stop $IMAGE_NAME
                 docker rm $IMAGE_NAME
               '''
             }
          }
     }
    }
}
